//! DNS configuration management
//!
//! Switches system DNS servers when VPN connects and restores them on disconnect.
//! Supports macOS (networksetup) and Linux (resolv.conf).

use crate::Error;

/// DNS configuration to apply
#[derive(Debug, Clone)]
pub struct DnsConfig {
    /// DNS server addresses (e.g., ["1.1.1.1", "8.8.8.8"])
    pub servers: Vec<String>,
}

impl DnsConfig {
    /// Create a new DNS config
    pub fn new(servers: Vec<String>) -> Self {
        Self { servers }
    }

    /// Check if DNS config is empty (no servers specified)
    pub fn is_empty(&self) -> bool {
        self.servers.is_empty()
    }
}

/// Saved DNS state for restoration on cleanup
#[derive(Debug)]
pub struct DnsState {
    #[cfg(target_os = "macos")]
    /// Original DNS per network service: (service_name, original_servers)
    pub original_dns: Vec<(String, Vec<String>)>,

    #[cfg(target_os = "linux")]
    /// Path to backup of /etc/resolv.conf
    pub backup_path: Option<std::path::PathBuf>,

    #[cfg(not(any(target_os = "macos", target_os = "linux")))]
    _placeholder: (),
}

/// Setup DNS servers on the system
///
/// Returns a DnsState that must be passed to `cleanup_dns()` to restore original settings.
#[cfg(target_os = "macos")]
pub fn setup_dns(config: &DnsConfig) -> Result<DnsState, Error> {
    if config.is_empty() {
        return Err(Error::Dns("No DNS servers specified".to_string()));
    }

    let services = get_active_network_services()?;
    let mut original_dns = Vec::new();

    for service in &services {
        let current = get_current_dns(service)?;
        original_dns.push((service.clone(), current));

        // Set new DNS servers
        let mut args = vec!["-setdnsservers".to_string(), service.clone()];
        args.extend(config.servers.clone());

        let output = std::process::Command::new("networksetup")
            .args(&args)
            .output()
            .map_err(|e| Error::Dns(format!("Failed to run networksetup: {}", e)))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            log::warn!("Failed to set DNS for '{}': {}", service, stderr);
        } else {
            log::info!("Set DNS for '{}': {:?}", service, config.servers);
        }
    }

    // Flush DNS cache
    let _ = std::process::Command::new("dscacheutil")
        .arg("-flushcache")
        .output();
    let _ = std::process::Command::new("killall")
        .args(["-HUP", "mDNSResponder"])
        .output();

    log::info!("DNS configured: {:?}", config.servers);

    Ok(DnsState { original_dns })
}

/// Setup DNS servers on the system (Linux)
#[cfg(target_os = "linux")]
pub fn setup_dns(config: &DnsConfig) -> Result<DnsState, Error> {
    use std::path::PathBuf;

    if config.is_empty() {
        return Err(Error::Dns("No DNS servers specified".to_string()));
    }

    let resolv_path = PathBuf::from("/etc/resolv.conf");
    let backup_path = PathBuf::from("/etc/resolv.conf.gatekeeper-backup");

    // Backup current resolv.conf
    if resolv_path.exists() {
        std::fs::copy(&resolv_path, &backup_path)
            .map_err(|e| Error::Dns(format!("Failed to backup resolv.conf: {}", e)))?;
    }

    // Write new resolv.conf
    let mut content = String::from("# Generated by GatekeeperVPN\n");
    for server in &config.servers {
        content.push_str(&format!("nameserver {}\n", server));
    }

    std::fs::write(&resolv_path, &content)
        .map_err(|e| Error::Dns(format!("Failed to write resolv.conf: {}", e)))?;

    log::info!("DNS configured: {:?}", config.servers);

    Ok(DnsState {
        backup_path: Some(backup_path),
    })
}

/// Setup DNS servers on the system (unsupported platform)
#[cfg(not(any(target_os = "macos", target_os = "linux")))]
pub fn setup_dns(config: &DnsConfig) -> Result<DnsState, Error> {
    if config.is_empty() {
        return Err(Error::Dns("No DNS servers specified".to_string()));
    }
    log::warn!("DNS configuration not supported on this platform");
    Ok(DnsState { _placeholder: () })
}

/// Restore original DNS settings
#[cfg(target_os = "macos")]
pub fn cleanup_dns(state: &DnsState) -> Result<(), Error> {
    for (service, original_servers) in &state.original_dns {
        let mut args = vec!["-setdnsservers".to_string(), service.clone()];

        if original_servers.is_empty()
            || (original_servers.len() == 1
                && original_servers[0].contains("There aren't any DNS Servers"))
        {
            // Restore to DHCP-provided DNS (empty = "Empty")
            args.push("Empty".to_string());
        } else {
            args.extend(original_servers.clone());
        }

        let output = std::process::Command::new("networksetup")
            .args(&args)
            .output()
            .map_err(|e| Error::Dns(format!("Failed to run networksetup: {}", e)))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            log::warn!("Failed to restore DNS for '{}': {}", service, stderr);
        } else {
            log::info!("Restored DNS for '{}'", service);
        }
    }

    // Flush DNS cache
    let _ = std::process::Command::new("dscacheutil")
        .arg("-flushcache")
        .output();
    let _ = std::process::Command::new("killall")
        .args(["-HUP", "mDNSResponder"])
        .output();

    log::info!("DNS restored to original settings");
    Ok(())
}

/// Restore original DNS settings (Linux)
#[cfg(target_os = "linux")]
pub fn cleanup_dns(state: &DnsState) -> Result<(), Error> {
    use std::path::PathBuf;

    if let Some(ref backup_path) = state.backup_path {
        let resolv_path = PathBuf::from("/etc/resolv.conf");

        if backup_path.exists() {
            std::fs::copy(backup_path, &resolv_path)
                .map_err(|e| Error::Dns(format!("Failed to restore resolv.conf: {}", e)))?;
            let _ = std::fs::remove_file(backup_path);
            log::info!("DNS restored from backup");
        }
    }

    Ok(())
}

/// Restore original DNS settings (unsupported platform)
#[cfg(not(any(target_os = "macos", target_os = "linux")))]
pub fn cleanup_dns(_state: &DnsState) -> Result<(), Error> {
    Ok(())
}

/// Get list of active network services (macOS)
#[cfg(target_os = "macos")]
fn get_active_network_services() -> Result<Vec<String>, Error> {
    let output = std::process::Command::new("networksetup")
        .arg("-listallnetworkservices")
        .output()
        .map_err(|e| Error::Dns(format!("Failed to list network services: {}", e)))?;

    if !output.status.success() {
        return Err(Error::Dns("networksetup failed".to_string()));
    }

    let stdout = String::from_utf8_lossy(&output.stdout);
    let services: Vec<String> = stdout
        .lines()
        .skip(1) // First line is "An asterisk (*) denotes..."
        .filter(|line| !line.starts_with('*')) // Skip disabled services
        .map(|s| s.to_string())
        .collect();

    Ok(services)
}

/// Get current DNS servers for a network service (macOS)
#[cfg(target_os = "macos")]
fn get_current_dns(service: &str) -> Result<Vec<String>, Error> {
    let output = std::process::Command::new("networksetup")
        .args(["-getdnsservers", service])
        .output()
        .map_err(|e| Error::Dns(format!("Failed to get DNS for '{}': {}", service, e)))?;

    let stdout = String::from_utf8_lossy(&output.stdout);
    let servers: Vec<String> = stdout.lines().map(|s| s.trim().to_string()).collect();

    Ok(servers)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_dns_config_creation() {
        let config = DnsConfig::new(vec!["1.1.1.1".to_string(), "8.8.8.8".to_string()]);
        assert_eq!(config.servers.len(), 2);
        assert_eq!(config.servers[0], "1.1.1.1");
        assert!(!config.is_empty());
    }

    #[test]
    fn test_dns_config_empty() {
        let config = DnsConfig::new(vec![]);
        assert!(config.is_empty());
    }
}
